plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.1'
	id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.pacifico'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

ext {
	set('liquibaseVersion', '4.25.0')
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	//R2DBC
	implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
	runtimeOnly 'io.r2dbc:r2dbc-mssql:1.0.0.RELEASE'

	//JDBC - SOLO para Liquibase
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	runtimeOnly 'com.microsoft.sqlserver:mssql-jdbc'

	//LIQUIBASE
	implementation "org.liquibase:liquibase-core:${liquibaseVersion}"

	//VALIDATION
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	//MAPSTRUCT
	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

	//LOMBOK
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
	testImplementation 'org.mockito:mockito-core'
	testImplementation 'org.mockito:mockito-junit-jupiter'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}