server:
  port: 8081

spring:
  application:
    name: ms-customer-management

  r2dbc:
    url: r2dbc:pool:sqlserver://localhost:1433/db_customer_management?encrypt=false
    username: sa
    password: Password123!

  # JDBC DataSource - SOLO para Liquibase
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=db_customer_management;encrypt=false;trustServerCertificate=true
    username: sa
    password: Password123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master-changelog.yaml
    liquibase-schema: schema_customer

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc: DEBUG